name: Unpack site zip

on:
  workflow_dispatch:            # adds the "Run workflow" button
    inputs:
      zip:
        description: "Zip filename (optional). Leave blank to use newest *.release.zip"
        required: false
  push:                         # also auto-run on push
    branches: [ "*" ]           # any branch
    paths:
      - "*.release.zip"         # zip must be in repo root
      - ".github/workflows/unzip.yml"

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Pick zip
        id: pick
        shell: bash
        run: |
          set -e
          FILE="${{ github.event.inputs.zip }}"
          if [ -z "$FILE" ]; then
            FILE=$(ls -t *.release.zip 2>/dev/null | head -n1 || true)
          fi
          if [ -z "$FILE" ]; then
            echo "No *.release.zip found in repo root"; exit 1
          fi
          echo "file=$FILE" >> "$GITHUB_OUTPUT"
          echo "Using: $FILE"

      - name: Unzip into repo root
        run: |
          unzip -o "${{ steps.pick.outputs.file }}" -d .
          rm -f "${{ steps.pick.outputs.file }}"

      - name: Commit unzipped site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"; exit 0
          fi
          git commit -m "Unpacked ${{ steps.pick.outputs.file }}"
          git push
