name: Unzip site release

on:
  push:
    paths:
      - "*.release.zip"

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip latest release
        run: |
          FILE=$(ls -t *.release.zip | head -n1)
          echo "Unzipping $FILE..."
          unzip -o "$FILE" -d .
          rm "$FILE"

      - name: Commit unzipped site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Unpacked site release" || echo "No changes to commit"
          git push
